"""Модуль `core/migrations/0002_remove_contactinfo_google_map_url_and_more.py` застосунку `core`.

Містить код проєкту Avelon Healthcare та відповідає за частину бізнес-логіки, налаштувань, форм, моделей, представлень або допоміжних сервісів.
Документація в модулі додана українською мовою для полегшення підтримки, читання коду та генерації технічної документації.
"""

# Generated by Django 6.0.4 on 2026-04-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    """Клас `Migration` інкапсулює повʼязану логіку проєкту.

    Базові класи: `migrations.Migration`.
    Використовується для опису доменної сутності, форми, адміністративної конфігурації, сервісу або представлення залежно від місця використання.
    """
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='google_map_url',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='google_map_embed_url',
            field=models.TextField(blank=True, verbose_name='Google Maps Embed URL'),
        ),
    ]
