"""Модуль `accounts/migrations/0004_alter_user_discount.py` застосунку `accounts`.

Містить код проєкту Avelon Healthcare та відповідає за частину бізнес-логіки, налаштувань, форм, моделей, представлень або допоміжних сервісів.
Документація в модулі додана українською мовою для полегшення підтримки, читання коду та генерації технічної документації.
"""

# Generated by Django 6.0.4 on 2026-04-21 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    """Клас `Migration` інкапсулює повʼязану логіку проєкту.

    Базові класи: `migrations.Migration`.
    Використовується для опису доменної сутності, форми, адміністративної конфігурації, сервісу або представлення залежно від місця використання.
    """
    dependencies = [
        ('accounts', '0003_user_pending_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Знижка, %'),
        ),
    ]
