# Generated by Django 6.0.4 on 2026-04-24 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефону має бути у форматі +380XXXXXXXXX', regex='^\\+380\\d{9}$')], verbose_name='Номер телефону'),
        ),
    ]
