"""Модуль `appointments/migrations/0002_appointment_email_appointment_full_name_and_more.py` застосунку `appointments`.

Містить код проєкту Avelon Healthcare та відповідає за частину бізнес-логіки, налаштувань, форм, моделей, представлень або допоміжних сервісів.
Документація в модулі додана українською мовою для полегшення підтримки, читання коду та генерації технічної документації.
"""

# Generated by Django 6.0.4 on 2026-04-15 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    """Клас `Migration` інкапсулює повʼязану логіку проєкту.

    Базові класи: `migrations.Migration`.
    Використовується для опису доменної сутності, форми, адміністративної конфігурації, сервісу або представлення залежно від місця використання.
    """
    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ПІБ'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
