"""Модуль `appointments/migrations/0004_remove_appointment_full_name_and_more.py` застосунку `appointments`.

Містить код проєкту Avelon Healthcare та відповідає за частину бізнес-логіки, налаштувань, форм, моделей, представлень або допоміжних сервісів.
Документація в модулі додана українською мовою для полегшення підтримки, читання коду та генерації технічної документації.
"""

# Generated by Django 6.0.4 on 2026-04-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    """Клас `Migration` інкапсулює повʼязану логіку проєкту.

    Базові класи: `migrations.Migration`.
    Використовується для опису доменної сутності, форми, адміністративної конфігурації, сервісу або представлення залежно від місця використання.
    """
    dependencies = [
        ('appointments', '0003_remove_appointment_full_name_appointment_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='По батькові'),
        ),
    ]
