"""Модуль `orders/migrations/0004_remove_order_full_name_order_first_name_and_more.py` застосунку `orders`.

Містить код проєкту Avelon Healthcare та відповідає за частину бізнес-логіки, налаштувань, форм, моделей, представлень або допоміжних сервісів.
Документація в модулі додана українською мовою для полегшення підтримки, читання коду та генерації технічної документації.
"""

# Generated by Django 6.0.4 on 2026-04-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    """Клас `Migration` інкапсулює повʼязану логіку проєкту.

    Базові класи: `migrations.Migration`.
    Використовується для опису доменної сутності, форми, адміністративної конфігурації, сервісу або представлення залежно від місця використання.
    """
    dependencies = [
        ('orders', '0003_order_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Прізвище'),
        ),
        migrations.AddField(
            model_name='order',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='По батькові'),
        ),
    ]
